<?php

namespace uqpay\payment\sdk\config;
require_once 'baseConfig.php';

class paygateConfig extends baseConfig
{
    var $apiRoot = "https://paygate.uqpay.com";

    public function getRSA()
    {
        return parent::getRSA(); // TODO: Change the autogenerated stub
    }

    public function __construct($config)
    {
        $this->apiRoot=$config["apiRoot"];
    }

//set方法
    public function __set($name, $value)
    {
        $this->$name = $value;
    }

    //get方法
    public function __get($name)
    {
        if (!isset($this->$name)) {
            //未设置
            $this->$name = "";
        }
        return $this->$name;
    }
}